/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER C
 */
public class Comment extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Comment
     */
    
    String TodayDate = null;
    String NowTime = null;
    String User = null;
    String AccountNo = null;
    String GetUser = null;
    int Serial = 0;
    String Com_Type = null;
    String Comment = null;
    int check = 0;
    
    public Comment() {
        initComponents();
        
        Load();        
    }

    public Comment(String User , String AccountNo) {
        initComponents();
        
        this.User = User;
        this.AccountNo = AccountNo;
        
        Load();        
    }
    
    public void Load(){
        String url="jdbc:mysql://127.0.0.1/comment";
        String user="root";
        String pass="";
        PreparedStatement ps = null;
        
        try{
            
            Connection conn= DriverManager.getConnection(url, user, pass);
            Statement stmt=conn.createStatement();
            String sql = null;
            
            sql = "select Serial_No , User_Name , Topic , Experience , Comment , Reply from public";
            
            ResultSet res = stmt.executeQuery(sql); 
            Public_Comment.setModel(DbUtils.resultSetToTableModel(res));
            
            sql = "select Serial_No , User_Name , Topic , Experience , Comment , Reply from private where User_Name = '"+User+"' and Account_No = '"+AccountNo+"'";
            
            res = stmt.executeQuery(sql); 
            Private_Comment.setModel(DbUtils.resultSetToTableModel(res));
            
            check = 0;
            
        }catch(SQLException e){
        
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentText = new javax.swing.JTextArea();
        CommentSubmit = new javax.swing.JButton();
        CommentBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CommentMale = new javax.swing.JRadioButton();
        CommentFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        Feedback = new javax.swing.JRadioButton();
        Suggestion = new javax.swing.JRadioButton();
        Objection = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Excellent = new javax.swing.JRadioButton();
        VeryGood = new javax.swing.JRadioButton();
        Good = new javax.swing.JRadioButton();
        Bad = new javax.swing.JRadioButton();
        VeryBad = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Public = new javax.swing.JRadioButton();
        Private = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Private_Comment = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Public_Comment = new javax.swing.JTable();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CommentIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 20));

        Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Comment");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 20));

        CommentText.setColumns(20);
        CommentText.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CommentText.setRows(5);
        CommentText.setToolTipText("Write your comment");
        jScrollPane1.setViewportView(CommentText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 150));

        CommentSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CommentSubmit.setText("Submit");
        CommentSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(CommentSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 140, 40));

        CommentBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CommentBack.setText("Back");
        CommentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentBackActionPerformed(evt);
            }
        });
        getContentPane().add(CommentBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email.setText("@gmail.com");
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));

        CommentMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(CommentMale);
        CommentMale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CommentMale.setText("Male");
        getContentPane().add(CommentMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 60, 20));

        CommentFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(CommentFemale);
        CommentFemale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CommentFemale.setText("Female");
        CommentFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(CommentFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Age");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Topic of Comment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 20));

        Age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, 30));

        Feedback.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Feedback);
        Feedback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Feedback.setText("Feedback");
        getContentPane().add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, 20));

        Suggestion.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Suggestion);
        Suggestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Suggestion.setText("Suggestion");
        getContentPane().add(Suggestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, 20));

        Objection.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(Objection);
        Objection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Objection.setText("Objection");
        Objection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjectionActionPerformed(evt);
            }
        });
        getContentPane().add(Objection, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Experience");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 100, 20));

        Excellent.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Excellent);
        Excellent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Excellent.setText("Excellent");
        getContentPane().add(Excellent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        VeryGood.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(VeryGood);
        VeryGood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VeryGood.setText("Very Good");
        getContentPane().add(VeryGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        Good.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Good);
        Good.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Good.setText("Good");
        getContentPane().add(Good, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        Bad.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(Bad);
        Bad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bad.setText("Bad");
        getContentPane().add(Bad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        VeryBad.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(VeryBad);
        VeryBad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VeryBad.setText("Very Bad");
        getContentPane().add(VeryBad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Comment Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 120, -1));

        Public.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Public);
        Public.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Public.setText("Public");
        getContentPane().add(Public, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        Private.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(Private);
        Private.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Private.setText("Private");
        getContentPane().add(Private, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        Private_Comment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Topic", "Feelings", "Comment", "Reply"
            }
        ));
        Private_Comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Private_CommentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Private_Comment);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 770, 140));

        Public_Comment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Topic", "Feelings", "Comment", "Reply"
            }
        ));
        Public_Comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Public_CommentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Public_Comment);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 770, 200));

        Edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 140, 40));

        Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 660, 140, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Comment, Question or Suggeasion");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Welcome to the Comment Section");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Public Comments");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Your Private Comments");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 457, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/comm1.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ticket_logo.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/comm2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1200, -1));

        CommentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        getContentPane().add(CommentIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CommentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentBackActionPerformed
        // TODO add your handling code here:
        new Menu(User , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CommentBackActionPerformed

    private void CommentSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentSubmitActionPerformed
        
        String sql = null;
        String Gender = null, CommentType = null, Experience = null;
        int GenTemp = 0 , ComTemp = 0 , ExpTemp = 0 , type = 0;

        if(CommentMale.isSelected())
        {
             Gender = CommentMale.getText();
             GenTemp = 1;
        }
        if(CommentFemale.isSelected())
        {
             Gender = CommentFemale.getText();
             GenTemp = 2;
        }

        if(Feedback.isSelected())
        {
              CommentType = Feedback.getText();
              ComTemp = 1;
        }
        if(Suggestion.isSelected())
        {
              CommentType = Suggestion.getText();
              ComTemp = 2;
        }
        if(Objection.isSelected())
        {
              CommentType = Objection.getText();
              ComTemp = 3;
        }

        if(Excellent.isSelected())
        {
               Experience = Excellent.getText();
               ExpTemp = 1;
        }
        if(VeryGood.isSelected())
        {
               Experience = VeryGood.getText();
               ExpTemp = 2;
        }
        if(Good.isSelected())
        {
               Experience = Good.getText();
               ExpTemp = 3;
        }
        if(Bad.isSelected())
        {
               Experience = Bad.getText();
               ExpTemp = 4;
        }
        if(VeryBad.isSelected())
        {
               Experience = VeryBad.getText();
               ExpTemp = 5;
        }
        
        if(Public.isSelected() || Private.isSelected()){
            type = 1;
        }
            
                    
        if(Name.getText().isEmpty() || Age.getText().isEmpty() || Email.getText().equals("@gmail.com") || Email.getText().isEmpty() || GenTemp == 0 || ComTemp == 0 || ExpTemp == 0 || type == 0 || CommentText.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter the all the Information !");
         }
        else{
            
            try{
                
                int Age_Temp = Integer.parseInt(Age.getText());
                
                String url="jdbc:mysql://127.0.0.1/comment";
                String user="root";
                String pass="";
                PreparedStatement ps = null;

                try{

                    Connection conn= DriverManager.getConnection(url, user, pass);

                    
                    if(Public.isSelected()){
                        sql = "insert into public values (null , '"+User+"' , '"+AccountNo+"' , '"+Name.getText()+"' ,'"+Age.getText()+"' ,'"+Email.getText()+"' ,'"+Gender+"' ,'"+CommentType+"' ,'"+Experience+"' ,'"+CommentText.getText()+"' , '')";
                    }else if(Private.isSelected()){
                        sql = "insert into private values (null , '"+User+"' , '"+AccountNo+"' , '"+Name.getText()+"' ,'"+Age.getText()+"' ,'"+Email.getText()+"' ,'"+Gender+"' ,'"+CommentType+"' ,'"+Experience+"' ,'"+CommentText.getText()+"' , '')";
                    }
                    
                        PreparedStatement pstmt = conn.prepareStatement(sql);

                        int x = pstmt.executeUpdate(sql);

                        if(ComTemp == 1)
                            JOptionPane.showMessageDialog(null, "Thanks for Your Feedback");
                        if(ComTemp == 2)
                            JOptionPane.showMessageDialog(null, "Thanks for Your Suggestion");
                        if(ComTemp == 3)
                            JOptionPane.showMessageDialog(null, "Thanks for Your Objection");

                        new ThankYou(User , AccountNo).setVisible(true);
                        dispose();


                }catch(SQLException e){

                    JOptionPane.showMessageDialog(null,e);
                    System.out.println(e);

                }
                
            }catch(Exception e){

                    JOptionPane.showMessageDialog(null, "Enter a Valid Age !");
                    System.out.println(e);

            }
        }
        
    }//GEN-LAST:event_CommentSubmitActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void CommentFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentFemaleActionPerformed

    private void ObjectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObjectionActionPerformed

    private void Public_CommentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Public_CommentMouseClicked
        // TODO add your handling code here:
        int i = Public_Comment.getSelectedRow();
        TableModel model = Public_Comment.getModel();
        Serial = (int) model.getValueAt(i, 0);
        GetUser = (String) model.getValueAt(i, 1);
        Comment = (String) model.getValueAt(i, 4);
        Com_Type = "Public";
        check = 1;
        
        String url="jdbc:mysql://127.0.0.1/comment";
        String user="root";
        String pass="";
        PreparedStatement ps = null;
        
        try{
            
            Connection conn= DriverManager.getConnection(url, user, pass);
            Statement stmt=conn.createStatement();
            String sql = null;
            
            sql = "select Serial_No , User_Name , Topic , Experience , Comment , Reply from private where User_Name = '"+User+"' and Account_No = '"+AccountNo+"'";
            
            ResultSet res = stmt.executeQuery(sql); 
            Private_Comment.setModel(DbUtils.resultSetToTableModel(res));
            
            
        }catch(SQLException e){
        
            System.out.println(e);
        }
        
    }//GEN-LAST:event_Public_CommentMouseClicked

    private void Private_CommentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Private_CommentMouseClicked
        // TODO add your handling code here:
        int i = Private_Comment.getSelectedRow();
        TableModel model = Private_Comment.getModel();
        Serial = (int) model.getValueAt(i, 0);
        GetUser = (String) model.getValueAt(i, 1);
        Comment = (String) model.getValueAt(i, 4);
        Com_Type = "Private";
        check = 1;
        
        String url="jdbc:mysql://127.0.0.1/comment";
        String user="root";
        String pass="";
        PreparedStatement ps = null;
        
        try{
            
            Connection conn= DriverManager.getConnection(url, user, pass);
            Statement stmt=conn.createStatement();
            String sql = null;
            
            sql = "select Serial_No , User_Name , Topic , Experience , Comment , Reply from public";
            
            ResultSet res = stmt.executeQuery(sql); 
            Public_Comment.setModel(DbUtils.resultSetToTableModel(res));
            
        }catch(SQLException e){
        
            System.out.println(e);
        }
        
    }//GEN-LAST:event_Private_CommentMouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        
        if(check == 0){
            JOptionPane.showMessageDialog(null, "Select your comment to edit !");
            
        }else if(GetUser.equals(User)){
            new Edit_Comment(String.valueOf(Serial) , Com_Type , GetUser , AccountNo , Comment).setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "This is not your comment !");
            JOptionPane.showMessageDialog(null, "You can edit only your comment !");
        }
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:        
        if(check == 0){
            JOptionPane.showMessageDialog(null, "Select your comment to delete !");
            
        }else if(GetUser.equals(User)){
            
            String url="jdbc:mysql://127.0.0.1/comment";
            String user="root";
            String pass="";
            PreparedStatement ps = null;

            try{
                Connection conn= DriverManager.getConnection(url, user, pass);
                String sql = null;
                
                if(Com_Type.equals("Public"))
                    sql = "delete from Public where Serial_No = '"+Serial+"'";
                else
                    sql = "delete from Private where Serial_No = '"+Serial+"'";
                
                int result = JOptionPane.showConfirmDialog(this,"Do you want to delete ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                
                if(result == JOptionPane.YES_OPTION){

                      PreparedStatement pstmt = conn.prepareStatement(sql);
                      pstmt.executeUpdate(sql); 
                      JOptionPane.showMessageDialog(null, "Your comment has been deleted !");
                }
                
                Load();
                
             }catch(Exception e){}
        }else{
            JOptionPane.showMessageDialog(null, "This is not your comment !");
            JOptionPane.showMessageDialog(null, "You can delete only your comment !");
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JRadioButton Bad;
    private javax.swing.JButton CommentBack;
    private javax.swing.JRadioButton CommentFemale;
    private javax.swing.JLabel CommentIcon;
    private javax.swing.JRadioButton CommentMale;
    private javax.swing.JButton CommentSubmit;
    private javax.swing.JTextArea CommentText;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Excellent;
    private javax.swing.JRadioButton Feedback;
    private javax.swing.JRadioButton Good;
    private javax.swing.JTextField Name;
    private javax.swing.JRadioButton Objection;
    private javax.swing.JRadioButton Private;
    private javax.swing.JTable Private_Comment;
    private javax.swing.JRadioButton Public;
    private javax.swing.JTable Public_Comment;
    private javax.swing.JRadioButton Suggestion;
    private javax.swing.JRadioButton VeryBad;
    private javax.swing.JRadioButton VeryGood;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
