/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject;

import java.awt.Cursor;

/**
 *
 * @author USER C
 */
public class Developers extends javax.swing.JFrame {

    /**
     * Creates new form Developers
     */
    String User_Name = null;
    String AccountNo = null;
    
    public Developers() {
        initComponents();
    }

    public Developers(String User_Name , String AccountNo) {
        initComponents();
    
        this.User_Name = User_Name;
        this.AccountNo = AccountNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Developers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Developers :: RAR Brotherhood");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Developers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Developer.jpg"))); // NOI18N
        Developers.setToolTipText("Click to Go Back");
        Developers.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DevelopersMouseMoved(evt);
            }
        });
        Developers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevelopersActionPerformed(evt);
            }
        });
        getContentPane().add(Developers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 475));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DevelopersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevelopersActionPerformed
        
        new ProjectDetails(User_Name , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DevelopersActionPerformed

    private void DevelopersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DevelopersMouseMoved
        
        Cursor cursor;
        cursor = new Cursor(Cursor.HAND_CURSOR);
        Developers.setCursor(cursor);
    }//GEN-LAST:event_DevelopersMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Developers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Developers;
    // End of variables declaration//GEN-END:variables
}
