/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER C
 */
public class GetMoneyAmount extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Payment
     */
    int TicketFare = 0;
    int PenaltyMoney = 0;
    int RestMoney = 0;
    String User_Name = null;
    String AccountNo = null;
    
    String MobileNo = null;
    String Keyword = null;
    
    public GetMoneyAmount() {
        initComponents();
    }
    
    /**
     *
     * @param MobileNo
     * @param Fare
     * @param Keyword
     */
    public GetMoneyAmount(String MobileNo , String Fare , String Keyword , String User_Name , String AccountNo) {
        initComponents();
        
        this.MobileNo = MobileNo;
        this.Keyword = Keyword;
        this.User_Name = User_Name;
        this.AccountNo = AccountNo;
        
        TicketFare = Integer.parseInt(Fare);
        PenaltyMoney = (int) (TicketFare * 0.15);
        RestMoney = TicketFare - PenaltyMoney;
        
        TicketPrize.setText(Fare);
        Penalty.setText(String.valueOf(PenaltyMoney));
        GetMoney.setText(String.valueOf(RestMoney));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Agreed = new javax.swing.JButton();
        TicketPrize = new javax.swing.JTextField();
        Penalty = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        GetMoney = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Payment_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Ticket Prize");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 50));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setText("Penalty ( 15% )");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, 50));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("After All");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 130, 50));

        Agreed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Agreed.setText("Agreed");
        Agreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreedActionPerformed(evt);
            }
        });
        getContentPane().add(Agreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 150, 40));

        TicketPrize.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        TicketPrize.setEnabled(false);
        TicketPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketPrizeActionPerformed(evt);
            }
        });
        getContentPane().add(TicketPrize, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 220, 50));

        Penalty.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Penalty.setEnabled(false);
        Penalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenaltyActionPerformed(evt);
            }
        });
        getContentPane().add(Penalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 50));

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 140, 40));

        GetMoney.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        GetMoney.setEnabled(false);
        GetMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMoneyActionPerformed(evt);
            }
        });
        getContentPane().add(GetMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, 50));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("Taka");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 50, 50));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("Taka");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, 50));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setText("Taka");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Rest Money");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lebel_mini.JPG"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 530, -1));

        Payment_Icon.setBackground(new java.awt.Color(255, 255, 255));
        Payment_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        getContentPane().add(Payment_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TicketPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketPrizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketPrizeActionPerformed

    private void PenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenaltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenaltyActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        
        new Menu(User_Name , AccountNo).setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    @SuppressWarnings({"deprecation", "deprecation"})
    private void AgreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreedActionPerformed
        
        new GetMoney_Media(MobileNo , Keyword , GetMoney.getText() , User_Name , AccountNo).setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_AgreedActionPerformed

    private void GetMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetMoneyAmount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agreed;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField GetMoney;
    private javax.swing.JLabel Payment_Icon;
    private javax.swing.JTextField Penalty;
    private javax.swing.JTextField TicketPrize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
