/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER C
 */
public class GetMoneyAccount extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Payment
     */
    String MobileNumber = "01826084705";
    String Password = "12345";
    String GetMoney = null;
    String MobileNo = null;
    String Keyword = null;
    String CurrentAmount = null;
    String User_Name = null;
    String AccountNo = null;
    
    public GetMoneyAccount() {
        initComponents();
    }
    
    public GetMoneyAccount(String Medium , String MobileNo , String Keyword , String GetMoney , String User_Name , String AccountNo) {
        initComponents();
        
        GetMoneyMedium.setText(Medium);
        this.MobileNo = MobileNo;
        this.Keyword = Keyword;
        this.GetMoney = GetMoney;
        this.User_Name = User_Name;
        this.AccountNo = AccountNo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        GetMoneyMedium = new javax.swing.JTextField();
        Payment_MobileNumber = new javax.swing.JTextField();
        Payment_Password = new javax.swing.JPasswordField();
        Cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ShowPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Payment_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 50));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, 50));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 130, 50));

        Confirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 150, 40));

        GetMoneyMedium.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        GetMoneyMedium.setEnabled(false);
        GetMoneyMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMoneyMediumActionPerformed(evt);
            }
        });
        getContentPane().add(GetMoneyMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 250, 50));

        Payment_MobileNumber.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        Payment_MobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payment_MobileNumberActionPerformed(evt);
            }
        });
        getContentPane().add(Payment_MobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 250, 50));

        Payment_Password.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        getContentPane().add(Payment_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 250, 50));

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Medium to Receive Money");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 40));

        ShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        ShowPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lebel_mini.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 70));

        Payment_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        getContentPane().add(Payment_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 517));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetMoneyMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMoneyMediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetMoneyMediumActionPerformed

    private void Payment_MobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payment_MobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Payment_MobileNumberActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        
        new Menu(User_Name , AccountNo).setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    @SuppressWarnings({"deprecation", "deprecation"})
    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        
        String url="jdbc:mysql://127.0.0.1/payment";
        String user="root";
        String pass="";
        
        try{
            
            Connection conn= DriverManager.getConnection(url, user, pass);
            Statement stmt=conn.createStatement();
            String sql;
            sql = "select * from payment_account where Account_Type = '"+GetMoneyMedium.getText()+"' and Mobile_Number = '"+Payment_MobileNumber.getText()+"'";
            ResultSet res = stmt.executeQuery(sql);
                        
            while(res.next()){               
                
                CurrentAmount = res.getString("Amount");
            }
            
            
        }catch(SQLException e){
        
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error !!!");
        }
        
        
        if(GetMoneyMedium.getText().equals("BKash") && Payment_MobileNumber.getText().equals(MobileNumber) && Payment_Password.getText().equals(Password)){
            new BKash_GetMoneyConfirmation(CurrentAmount , GetMoneyMedium.getText(), Payment_MobileNumber.getText() , MobileNo , Keyword , GetMoney , User_Name , AccountNo).setVisible(true);
            dispose();
        }
        else if(GetMoneyMedium.getText().equals("Nogad") && Payment_MobileNumber.getText().equals(MobileNumber) && Payment_Password.getText().equals(Password)){
            new Nogad_GetMoneyConfirmation(CurrentAmount , GetMoneyMedium.getText(), Payment_MobileNumber.getText() , MobileNo , Keyword , GetMoney , User_Name , AccountNo).setVisible(true);
            dispose();
        }
        else if(GetMoneyMedium.getText().equals("Rocket") && Payment_MobileNumber.getText().equals(MobileNumber) && Payment_Password.getText().equals(Password)){
            new Rocket_GetMoneyConfirmation(CurrentAmount , GetMoneyMedium.getText(), Payment_MobileNumber.getText() , MobileNo , Keyword , GetMoney , User_Name , AccountNo).setVisible(true);
            dispose();
        }
        else if(GetMoneyMedium.getText().equals("SureCash") && Payment_MobileNumber.getText().equals(MobileNumber) && Payment_Password.getText().equals(Password)){
            new SureCash_GetMoneyConfirmation(CurrentAmount , GetMoneyMedium.getText(), Payment_MobileNumber.getText() , MobileNo , Keyword , GetMoney , User_Name , AccountNo).setVisible(true);
            dispose();
        }
        else if(Payment_MobileNumber.getText().isEmpty() || Payment_Password.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Provide all the Information");
        }
        else if(Payment_MobileNumber.getText().isEmpty() && Payment_Password.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Provide all the Information");
        }        
        else{
            JOptionPane.showMessageDialog(null, "Cheak the Mobile Number & Password Again");
        }
        
    }//GEN-LAST:event_ConfirmActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ShowPassword.isSelected())
        {
            Payment_Password.setEchoChar((char) 0);
        }else{
            Payment_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetMoneyAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetMoneyAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Confirm;
    private javax.swing.JTextField GetMoneyMedium;
    private javax.swing.JLabel Payment_Icon;
    private javax.swing.JTextField Payment_MobileNumber;
    private javax.swing.JPasswordField Payment_Password;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
