/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER C
 */
public class Nogad_GetMoneyConfirmation extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Payment
     */
    int PresentAmount = 0;
    int RestMoney = 0;
    String Rest_Amount = null;
    String user="root";
    String pass="";
    String Account_MobileNumber = null;
    String MobileNo = null;
    String Keyword = null;
    String User_Name = null;
    String AccountNo = null;
    String PaymentMedium = null;
    
    public Nogad_GetMoneyConfirmation() {
        initComponents();
    }
    
    public Nogad_GetMoneyConfirmation(String Amount , String Medium , String Account_MobileNumber , String MobileNo , String Keyword , String GetMoney , String User_Name , String AccountNo) {
        initComponents();
        
        CurrentAmount.setText(Amount);
        PaymentMedium = Medium;
        this.Account_MobileNumber = Account_MobileNumber;
        this.MobileNo = MobileNo;
        this.GetMoney.setText(GetMoney);
        this.Keyword = Keyword;
        this.User_Name = User_Name;
        this.AccountNo = AccountNo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Get = new javax.swing.JButton();
        CurrentAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GetMoney = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PaymentConfirmation_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Money Receive Confirmation");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 30));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Present Amount");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 50));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setText("Get Money");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, 50));

        Get.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Get.setText("Get");
        Get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetActionPerformed(evt);
            }
        });
        getContentPane().add(Get, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 150, 40));

        CurrentAmount.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        CurrentAmount.setEnabled(false);
        CurrentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentAmountActionPerformed(evt);
            }
        });
        getContentPane().add(CurrentAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 200, 50));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel5.setText("Taka");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lebel_mini.JPG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        GetMoney.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        GetMoney.setEnabled(false);
        GetMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMoneyActionPerformed(evt);
            }
        });
        getContentPane().add(GetMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 200, 50));

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 140, 40));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setText("Taka");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 40, 50));

        PaymentConfirmation_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        getContentPane().add(PaymentConfirmation_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentAmountActionPerformed

    private void GetMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetMoneyActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        
        new Menu(User_Name , AccountNo).setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void GetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetActionPerformed
        
        PresentAmount = Integer.parseInt(CurrentAmount.getText());
        RestMoney = Integer.parseInt(GetMoney.getText());
        
        int result = JOptionPane.showConfirmDialog(this,"Do you want to Cancel the Ticket ?","Confirm",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
                
            if(result == JOptionPane.OK_OPTION){
                    String url="jdbc:mysql://127.0.0.1/ticket";
                    PreparedStatement ps = null;

                        try{

                            Connection conn= DriverManager.getConnection(url, user, pass);
                            String sql = null;

                                sql = "delete from ticket_list where Mobile_Number = '"+MobileNo+"' and Keyword = '"+Keyword+"'";
                                
                                PreparedStatement pstmt = conn.prepareStatement(sql);

                                pstmt.executeUpdate(sql);
                                
                                sql = "update all_tickets set Type = 'Cancelled' where Mobile_Number = '"+MobileNo+"' and Keyword = '"+Keyword+"'";

                                pstmt = conn.prepareStatement(sql);

                                pstmt.executeUpdate(sql);

                                PresentAmount = PresentAmount + RestMoney;
                                Rest_Amount = String.valueOf(PresentAmount);



                                        String url2="jdbc:mysql://127.0.0.1/payment";
                                        try{
                                            Connection con= DriverManager.getConnection(url2, user, pass);
                                            Statement stmt;
                                            stmt = con.createStatement();
                                            String sql2 = null;

                                            sql2 = "update payment_account set Amount = '"+Rest_Amount+"' where Account_Type = 'Nogad'";

                                            stmt.executeUpdate(sql2);

                                        }catch(SQLException e){

                                             System.out.println(e);
                                             JOptionPane.showMessageDialog(null, "Error !!!!");
                                        }


                                        JOptionPane.showMessageDialog(null, "Your Ticket has been Cancelled !");
                                        JOptionPane.showMessageDialog(null, "The Money has been included in your Nogad Account !");
                                        new CurrentAmount(Rest_Amount , User_Name , AccountNo).setVisible(true);
                                        dispose();



                        }catch(SQLException e){

                            JOptionPane.showMessageDialog(null, "Enter the all the Information !");
                            System.out.println(e);

                        }
                }
                else{
                      new Menu().setVisible(true);
                }
        
        
        
      
        
    }//GEN-LAST:event_GetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nogad_GetMoneyConfirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField CurrentAmount;
    private javax.swing.JButton Get;
    private javax.swing.JTextField GetMoney;
    private javax.swing.JLabel PaymentConfirmation_Icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
