/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject;

import java.awt.Cursor;

/**
 *
 * @author USER C
 */
public class ProjectDetails extends javax.swing.JFrame {

    /**
     * Creates new form ProjectDetails
     */
    String User_Name = null;
    String AccountNo = null;
    
    public ProjectDetails() {
        initComponents();
    }

    public ProjectDetails(String User_Name , String AccountNo) {
        initComponents();
        
        this.User_Name = User_Name;
        this.AccountNo = AccountNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectDetails_requirements = new javax.swing.JButton();
        ProjectDetails_Features = new javax.swing.JButton();
        ProjectDetails_details = new javax.swing.JButton();
        ProjectDetails_developers = new javax.swing.JButton();
        ProjectDetails_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ProjectDetails_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProjectDetails_requirements.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProjectDetails_requirements.setText("Requirements");
        ProjectDetails_requirements.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProjectDetails_requirementsMouseMoved(evt);
            }
        });
        ProjectDetails_requirements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectDetails_requirementsActionPerformed(evt);
            }
        });
        getContentPane().add(ProjectDetails_requirements, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 250, 50));

        ProjectDetails_Features.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProjectDetails_Features.setText("Features");
        ProjectDetails_Features.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectDetails_FeaturesActionPerformed(evt);
            }
        });
        getContentPane().add(ProjectDetails_Features, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 250, 50));

        ProjectDetails_details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProjectDetails_details.setText("Details");
        ProjectDetails_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectDetails_detailsActionPerformed(evt);
            }
        });
        getContentPane().add(ProjectDetails_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 250, 50));

        ProjectDetails_developers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProjectDetails_developers.setText("Developers");
        ProjectDetails_developers.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ProjectDetails_developersMouseMoved(evt);
            }
        });
        ProjectDetails_developers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectDetails_developersActionPerformed(evt);
            }
        });
        getContentPane().add(ProjectDetails_developers, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 250, 50));

        ProjectDetails_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProjectDetails_back.setText("Main Menu");
        ProjectDetails_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectDetails_backActionPerformed(evt);
            }
        });
        getContentPane().add(ProjectDetails_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 220, 50));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 26)); // NOI18N
        jLabel3.setText("Project Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lebel.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 640, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BR Logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 220, 300));

        ProjectDetails_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        getContentPane().add(ProjectDetails_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectDetails_developersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectDetails_developersActionPerformed
        
        new Developers(User_Name , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProjectDetails_developersActionPerformed

    private void ProjectDetails_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectDetails_backActionPerformed
        
        new Menu(User_Name , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProjectDetails_backActionPerformed

    private void ProjectDetails_requirementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectDetails_requirementsActionPerformed
        
        new Requirements(User_Name , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProjectDetails_requirementsActionPerformed

    private void ProjectDetails_FeaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectDetails_FeaturesActionPerformed
               
        new Features(User_Name , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProjectDetails_FeaturesActionPerformed

    private void ProjectDetails_requirementsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectDetails_requirementsMouseMoved
        
        Cursor cursor;
        cursor = new Cursor(Cursor.HAND_CURSOR);
        ProjectDetails_requirements.setCursor(cursor);
        ProjectDetails_Features.setCursor(cursor);
        ProjectDetails_details.setCursor(cursor);
        ProjectDetails_developers.setCursor(cursor);
        ProjectDetails_back.setCursor(cursor);
    }//GEN-LAST:event_ProjectDetails_requirementsMouseMoved

    private void ProjectDetails_developersMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectDetails_developersMouseMoved
        
    }//GEN-LAST:event_ProjectDetails_developersMouseMoved

    private void ProjectDetails_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectDetails_detailsActionPerformed
        
        new Details1(User_Name , AccountNo).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ProjectDetails_detailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProjectDetails_Features;
    private javax.swing.JButton ProjectDetails_back;
    private javax.swing.JButton ProjectDetails_details;
    private javax.swing.JButton ProjectDetails_developers;
    private javax.swing.JLabel ProjectDetails_icon;
    private javax.swing.JButton ProjectDetails_requirements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
